server:
  port: ${PORT:3010}

spring:
  profiles:
    active: dev
  datasource:
    url: ${GRADE_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${GRADE_DB_USER}
    password: ${GRADE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${GRADE_OPENAI_KEY:#{null}}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

