debug: true
server:
  port: 3010

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-13t5bonxphxnh36q.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: https://grade.use3w.com

spring:
  datasource:
    url: ${GRADE_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${GRADE_DB_USER}
    password: ${GRADE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

userinfo_url: ${GRADE_USERINFO_URL}
