server:
  port: 3010

okta:
  oauth2:
    issuer: https://dev-13t5bonxphxnh36q.us.auth0.com/
    audience: https://grade.use3w.com

spring:
  profiles:
    active: dev
  datasource:
    url: ${GRADE_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${GRADE_DB_USER}
    password: ${GRADE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${GRADE_OPENAI_KEY}

userinfo_url: ${GRADE_USERINFO_URL}

