name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptium'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1  # Ensures the Gradle wrapper is present and valid

      # Step 4: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Step 5: Deploy to remote server via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Step 6: Copy the JAR file from the GitHub Actions runner to the remote server
            scp ./build/libs/*.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }}:/home/remoteuser/app/

            # Step 7: Run the application on the remote machine
            nohup java -jar /home/remoteuser/app/*.jar > /home/remoteuser/app/app.log 2>&1 &

      # Step 8: Clean up (Optional)
      - name: Clean up
        run: |
          # This step could be used for any cleanup after the deployment (optional)
          echo "Cleanup completed"
      # Step 3: Set up Gradle
