name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Step 2: Set up JDK for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Gradle
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v5

     # Step 4: Grant execute permissions for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Step 5: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Step 6: Upload jar to remote server via SSH
      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./build/libs/*.jar
          target: /home/actions/app/

      # Step 7: Deploy to remote server via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo -n systemctl stop gradeback.service || true
            sudo -n systemctl start gradeback.service
            sudo -n systemctl status gradeback.service
            echo "Deployment completed successfully!"