name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1  # Ensures the Gradle wrapper is present and valid

      # Step 3: Grant execute permissions for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Step 4: Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Step 5: Upload jar to remote server via SSH
      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./build/libs/*.jar
          target: /home/actions/app/

      # Step 6: Kill application running on port 3010
      - name: Kill application on port 3010
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            fuser -k 3010/tcp

      # Step 7: Deploy to remote server via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            nohup java -jar /home/actions/app/build/libs/*.jar > /home/actions/app/build/libs/app.log 2>&1 &

      # Step 8: Clean up (Optional)
      - name: Clean up
        run: |
          # This step could be used for any cleanup after the deployment (optional)
          echo "Cleanup completed"